
require("../Base");

Database = {};

Database.items = {
    "coin":{name:"万金币", },
    "summon_book":{name:"勇者契约书", },
    "league_war_horn":{name:"国战笑脸", },
    "league_war_life":{name:"国战旗帜", },
    "magical_girl_hook_2":{name:"资深魔女书", },
    "magical_girl_hook_3":{name:"传说魔女书", },
    "dungeon_dice":{name:"秘境骰子", },
    "hero_upgrade_card":{name:"主角进化卡", },
    "hero_upgrade_card_piece":{name:"主角进化卡碎片", piece: 50, },
    "special_coin":{name:"特典币", },
    "x_coin":{name:"暗金币", },
    "ticket_card_1":{name:"5点钻石", use:true, },
    "meal_lunch":{name:"豪华午餐", use:true, },
    "meal_supper":{name:"豪华晚餐", use:true, },
    "food_2":{name:"梅子饭团", },
    "food_3":{name:"爱心便当", },
    "food_4":{name:"魔能汉堡", },
    "food_5":{name:"泡椒喵蛋", },
    "food_6":{name:"龙肉", },
    "coin_card_1":{name:"5w金砖", use:true, },
    "coin_card_2":{name:"20w金砖", use:true, },
    "coin_card_3":{name:"88w金砖", use:true, },
    "hero_card_piece_2":{name:"绿色特定勇者卡碎片", piece:10, },
    "hero_card_piece_3":{name:"蓝色特定勇者卡碎片", piece:10, },
    "hero_card_piece_4":{name:"紫色特定勇者卡碎片", piece:10, },
    "hero_card_piece_5":{name:"橙色特定勇者卡碎片", piece:30, },
    "hero_card_piece_6":{name:"红色特定勇者卡碎片", piece:50, },
    "hero_card_piece_7":{name:"金色特定勇者卡碎片", piece:100, },
    "hero_card_random_2":{name:"绿色勇者卡", use:true, },
    "hero_card_random_3":{name:"蓝色勇者卡", use:true, },
    "hero_card_random_4":{name:"紫色勇者卡", use:true, },
    "hero_card_random_5":{name:"橙色勇者卡", use:true, },
    "hero_card_random_6":{name:"红色勇者卡", use:true, },
    "hero_card_random_7":{name:"金色勇者卡", use:true, },
    "hero_card_random_piece_2":{name:"绿色勇者卡碎片", piece:10, },
    "hero_card_random_piece_3":{name:"蓝色勇者卡碎片", piece:10, },
    "hero_card_random_piece_4":{name:"紫色勇者卡碎片", piece:10, },
    "hero_card_random_piece_5":{name:"橙色勇者卡碎片", piece:30, },
    "hero_card_random_piece_6":{name:"红色勇者卡碎片", piece:50, },
    "hero_card_random_piece_7":{name:"金色勇者卡碎片", piece:100, },
    "master_scroll_1":{name:"刺客专精", },
    "master_scroll_2":{name:"弓手专精", },
    "master_scroll_3":{name:"法师专精", },
    "master_scroll_4":{name:"战士专精", },
    "master_scroll_5":{name:"医者专精", },
    "sp_weapon_soul_stone":{name:"宝具魂石", },
    "sp_weapon_awake_stone":{name:"觉醒石", },
    "sp_weapon_material_1":{name:"刺客精华", },
    "sp_weapon_material_2":{name:"弓手精华", },
    "sp_weapon_material_3":{name:"法师精华", },
    "sp_weapon_material_4":{name:"战士精华", },
    "sp_weapon_material_5":{name:"医者精华", },
    "stone_atk_2":{name:"绿色强攻石", },
    "stone_crit_2":{name:"绿色致命石", },
    "stone_def_2":{name:"绿色守护石", },
    "stone_dodge_2":{name:"绿色精巧石", },
    "stone_hit_2":{name:"绿色鹰眼石", },
    "stone_hp_2":{name:"绿色生命石", },
    "stone_speed_2":{name:"绿色疾风石", },
    "stone_tenacity_2":{name:"绿色恩惠石", },
    "stone_atk_3":{name:"蓝色强攻石", },
    "stone_crit_3":{name:"蓝色致命石", },
    "stone_def_3":{name:"蓝色守护石", },
    "stone_dodge_3":{name:"蓝色精巧石", },
    "stone_hit_3":{name:"蓝色鹰眼石", },
    "stone_hp_3":{name:"蓝色生命石", },
    "stone_speed_3":{name:"蓝色疾风石", },
    "stone_tenacity_3":{name:"蓝色恩惠石", },
    "stone_piece_atk_3":{name:"蓝色强攻石碎片", piece:5, },
    "stone_piece_crit_3":{name:"蓝色致命石碎片", piece:5, },
    "stone_piece_def_3":{name:"蓝色守护石碎片", piece:5, },
    "stone_piece_dodge_3":{name:"蓝色精巧石碎片", piece:5, },
    "stone_piece_hit_3":{name:"蓝色鹰眼石碎片", piece:5, },
    "stone_piece_hp_3":{name:"蓝色生命石碎片", piece:5, },
    "stone_piece_speed_3":{name:"蓝色疾风石碎片", piece:5, },
    "stone_piece_tenacity_3":{name:"蓝色恩惠石碎片", piece:5, },
    "stone_atk_4":{name:"紫色强攻石", },
    "stone_crit_4":{name:"紫色致命石", },
    "stone_def_4":{name:"紫色守护石", },
    "stone_dodge_4":{name:"紫色精巧石", },
    "stone_hit_4":{name:"紫色鹰眼石", },
    "stone_hp_4":{name:"紫色生命石", },
    "stone_speed_4":{name:"紫色疾风石", },
    "stone_tenacity_4":{name:"紫色恩惠石", },
    "stone_piece_atk_4":{name:"紫色强攻石碎片", piece:10, },
    "stone_piece_crit_4":{name:"紫色致命石碎片", piece:10, },
    "stone_piece_def_4":{name:"紫色守护石碎片", piece:10, },
    "stone_piece_dodge_4":{name:"紫色精巧石碎片", piece:10, },
    "stone_piece_hit_4":{name:"紫色鹰眼石碎片", piece:10, },
    "stone_piece_hp_4":{name:"紫色生命石碎片", piece:10, },
    "stone_piece_speed_4":{name:"紫色疾风石碎片", piece:10, },
    "stone_piece_tenacity_4":{name:"紫色恩惠石碎片", piece:10, },
    "stone_atk_5":{name:"橙色强攻石", },
    "stone_crit_5":{name:"橙色致命石", },
    "stone_def_5":{name:"橙色守护石", },
    "stone_dodge_5":{name:"橙色精巧石", },
    "stone_hit_5":{name:"橙色鹰眼石", },
    "stone_hp_5":{name:"橙色生命石", },
    "stone_speed_5":{name:"橙色疾风石", },
    "stone_tenacity_5":{name:"橙色恩惠石", },
    "stone_piece_atk_5":{name:"橙色强攻石碎片", piece:20, },
    "stone_piece_crit_5":{name:"橙色致命石碎片", piece:20, },
    "stone_piece_def_5":{name:"橙色守护石碎片", piece:20, },
    "stone_piece_dodge_5":{name:"橙色精巧石碎片", piece:20, },
    "stone_piece_hit_5":{name:"橙色鹰眼石碎片", piece:20, },
    "stone_piece_hp_5":{name:"橙色生命石碎片", piece:20, },
    "stone_piece_speed_5":{name:"橙色疾风石碎片", piece:20, },
    "stone_piece_tenacity_5":{name:"橙色恩惠石碎片", piece:20, },
    "stone_atk_6":{name:"红色强攻石", },
    "stone_crit_6":{name:"红色致命石", },
    "stone_def_6":{name:"红色守护石", },
    "stone_dodge_6":{name:"红色精巧石", },
    "stone_hit_6":{name:"红色鹰眼石", },
    "stone_hp_6":{name:"红色生命石", },
    "stone_speed_6":{name:"红色疾风石", },
    "stone_tenacity_6":{name:"红色恩惠石", },
    "stone_piece_atk_6":{name:"红色强攻石碎片", piece:30, },
    "stone_piece_crit_6":{name:"红色致命石碎片", piece:30, },
    "stone_piece_def_6":{name:"红色守护石碎片", piece:30, },
    "stone_piece_dodge_6":{name:"红色精巧石碎片", piece:30, },
    "stone_piece_hit_6":{name:"红色鹰眼石碎片", piece:30, },
    "stone_piece_hp_6":{name:"红色生命石碎片", piece:30, },
    "stone_piece_speed_6":{name:"红色疾风石碎片", piece:30, },
    "stone_piece_tenacity_6":{name:"红色恩惠石碎片", piece:30, },
    "stone_atk_7":{name:"金色强攻石", },
    "stone_crit_7":{name:"金色致命石", },
    "stone_def_7":{name:"金色守护石", },
    "stone_dodge_7":{name:"金色精巧石", },
    "stone_hit_7":{name:"金色鹰眼石", },
    "stone_hp_7":{name:"金色生命石", },
    "stone_speed_7":{name:"金色疾风石", },
    "stone_tenacity_7":{name:"金色恩惠石", },
    "stone_piece_atk_7":{name:"金色强攻石碎片", piece:30, },
    "stone_piece_crit_7":{name:"金色致命石碎片", piece:30, },
    "stone_piece_def_7":{name:"金色守护石碎片", piece:30, },
    "stone_piece_dodge_7":{name:"金色精巧石碎片", piece:30, },
    "stone_piece_hit_7":{name:"金色鹰眼石碎片", piece:30, },
    "stone_piece_hp_7":{name:"金色生命石碎片", piece:30, },
    "stone_piece_speed_7":{name:"金色疾风石碎片", piece:30, },
    "stone_piece_tenacity_7":{name:"金色恩惠石碎片", piece:30, },
    "stone_piece_random_2":{name:"绿色随机石碎片", use:true, },
    "stone_piece_random_3":{name:"蓝色随机石碎片", use:true, },
    "stone_piece_random_4":{name:"紫色随机石碎片", use:true, },
    "stone_piece_random_5":{name:"橙色随机石碎片", use:true, },
    "stone_piece_random_6":{name:"红色随机石碎片", use:true, },
    "stone_piece_random_7":{name:"金色随机石碎片", use:true, },
    "equip_compose_4_any":{name:"神金锭", },
    "equip_compose_4_a":{name:"4阶武具图纸", },
    "equip_compose_4_b":{name:"4阶防具图纸", },
    "equip_compose_4_c":{name:"4阶饰品图纸", },
    "equip_compose_4_extra":{name:"4阶龙石", },
};

Database.equips = {
    "amulet":{name:"护身符"},
    "armor":{name:"护肩"},
    "boots":{name:"靴子"},
    "certificate":{name:"证书"},
    "legs":{name:"护腿"},
    "mask":{name:"面罩"},
    "pet":{name:"宠物"},
    "ring":{name:"戒指"},
    "shield":{name:"盾牌"},
    "weapon":{name:"武器"},
};

Database.heros = {
    "456123":3,
};

Database.goblin_item = {
    "0001":{item_id:"coin", count:1000, buy:2, },
    "0002":{item_id:"coin", count:500, buy:2, },
    "0003":{item_id:"summon_book", count:5, buy:1, },
    "0004":{item_id:"summon_book", count:2, buy:1, },
    "0005":{item_id:"stone_piece_random_3", count:100, buy:1, },
    "0006":{item_id:"stone_piece_random_4", count:100, buy:1, },
    "0007":{item_id:"stone_piece_random_5", count:100, buy:1, },
    "0008":{item_id:"stone_piece_random_6", count:100, buy:1, },
    "0009":{item_id:"stone_piece_random_7", count:100, buy:1, },
    "0010":{item_id:"food_2", count:30, buy:1, },
    "0011":{item_id:"food_3", count:30, buy:1, },
    "0012":{item_id:"food_4", count:30, buy:1, },
    "0013":{item_id:"food_5", count:30, buy:1, },
    "0014":{item_id:"food_6", count:30, buy:1, },
    "0015":{item_id:"dungeon_dice", count:5, buy:1, },
    "0016":{item_id:"hero_upgrade_card_piece", count:3, buy:1, },
    "0017":{item_id:"summon_book", count:5, buy:2, },
    "0018":{item_id:"summon_book", count:2, buy:2, },
    "0019":{item_id:"stone_piece_random_3", count:100, buy:2, },
    "0020":{item_id:"stone_piece_random_4", count:100, buy:2, },
    "0021":{item_id:"stone_piece_random_5", count:100, buy:2, },
    "0022":{item_id:"stone_piece_random_6", count:100, buy:2, },
    "0023":{item_id:"stone_piece_random_7", count:100, buy:2, },
    "0024":{item_id:"food_2", count:30, buy:2, },
    "0025":{item_id:"food_3", count:30, buy:2, },
    "0026":{item_id:"food_4", count:30, buy:2, },
    "0027":{item_id:"food_5", count:30, buy:2, },
    "0028":{item_id:"food_6", count:30, buy:2, },
    "0029":{item_id:"dungeon_dice", count:5, buy:2, },
    "0030":{item_id:"hero_upgrade_card_piece", count:3, buy:2, },
};

Database.goblin_reduce = {
    "209": 8,
    "210": 5,
    "211": 5,
    "212": 3,
};
