
require("../Base");

Database = {};

Database.goblinInfo = function(id) {
    var iId = Number(id) % 1000000;
    var reduceInfo = this.goblin_reduce[Math.floor(iId / 10000)];
    var itemInfo = this.goblin_item[iId % 10000];
    if (!reduceInfo || !itemInfo) {
        return null;
    }
    return {
        reduce: reduceInfo,
        itemName: itemInfo.item_id,
        buyCount: itemInfo.count,
        useDiamond: itemInfo.buy == 2,
    };
}

Database.items = {
    "coin":{name:"万金币", },
    "summon_book":{name:"勇者契约书", },
    "league_war_horn":{name:"国战笑脸", },
    "league_war_life":{name:"国战旗帜", },
    "magical_girl_hook_2":{name:"资深魔女书", },
    "magical_girl_hook_3":{name:"传说魔女书", },
    "dungeon_dice":{name:"秘境骰子", },
    "hero_upgrade_card":{name:"主角进化卡", },
    "hero_upgrade_card_piece":{name:"主角进化卡碎片", piece: 50, },
    "special_coin":{name:"特典币", },
    "x_coin":{name:"暗金币", },
    "ticket_card_1":{name:"5点钻石", use:true, },
    "meal_lunch":{name:"豪华午餐", use:true, },
    "meal_supper":{name:"豪华晚餐", use:true, },
    "food_2":{name:"梅子饭团", },
    "food_3":{name:"爱心便当", },
    "food_4":{name:"魔能汉堡", },
    "food_5":{name:"泡椒喵蛋", },
    "food_6":{name:"龙肉", },
    "coin_card_1":{name:"5w金砖", use:true, },
    "coin_card_2":{name:"20w金砖", use:true, },
    "coin_card_3":{name:"88w金砖", use:true, },
    "hero_card_piece_2":{name:"绿色特定勇者卡碎片", piece:10, },
    "hero_card_piece_3":{name:"蓝色特定勇者卡碎片", piece:10, },
    "hero_card_piece_4":{name:"紫色特定勇者卡碎片", piece:10, },
    "hero_card_piece_5":{name:"橙色特定勇者卡碎片", piece:30, },
    "hero_card_piece_6":{name:"红色特定勇者卡碎片", piece:50, },
    "hero_card_piece_7":{name:"金色特定勇者卡碎片", piece:100, },
    "hero_card_random_2":{name:"绿色勇者卡", use:true, },
    "hero_card_random_3":{name:"蓝色勇者卡", use:true, },
    "hero_card_random_4":{name:"紫色勇者卡", use:true, },
    "hero_card_random_5":{name:"橙色勇者卡", use:true, },
    "hero_card_random_6":{name:"红色勇者卡", use:true, },
    "hero_card_random_7":{name:"金色勇者卡", use:true, },
    "hero_card_random_piece_2":{name:"绿色勇者卡碎片", piece:10, },
    "hero_card_random_piece_3":{name:"蓝色勇者卡碎片", piece:10, },
    "hero_card_random_piece_4":{name:"紫色勇者卡碎片", piece:10, },
    "hero_card_random_piece_5":{name:"橙色勇者卡碎片", piece:30, },
    "hero_card_random_piece_6":{name:"红色勇者卡碎片", piece:50, },
    "hero_card_random_piece_7":{name:"金色勇者卡碎片", piece:100, },
    "master_scroll_1":{name:"刺客专精", },
    "master_scroll_2":{name:"弓手专精", },
    "master_scroll_3":{name:"法师专精", },
    "master_scroll_4":{name:"战士专精", },
    "master_scroll_5":{name:"医者专精", },
    "sp_weapon_soul_stone":{name:"宝具魂石", },
    "sp_weapon_awake_stone":{name:"觉醒石", },
    "sp_weapon_material_1":{name:"刺客精华", },
    "sp_weapon_material_2":{name:"弓手精华", },
    "sp_weapon_material_3":{name:"法师精华", },
    "sp_weapon_material_4":{name:"战士精华", },
    "sp_weapon_material_5":{name:"医者精华", },
    "stone_atk_2":{name:"绿色强攻石", },
    "stone_crit_2":{name:"绿色致命石", },
    "stone_def_2":{name:"绿色守护石", },
    "stone_dodge_2":{name:"绿色精巧石", },
    "stone_hit_2":{name:"绿色鹰眼石", },
    "stone_hp_2":{name:"绿色生命石", },
    "stone_speed_2":{name:"绿色疾风石", },
    "stone_tenacity_2":{name:"绿色恩惠石", },
    "stone_atk_3":{name:"蓝色强攻石", },
    "stone_crit_3":{name:"蓝色致命石", },
    "stone_def_3":{name:"蓝色守护石", },
    "stone_dodge_3":{name:"蓝色精巧石", },
    "stone_hit_3":{name:"蓝色鹰眼石", },
    "stone_hp_3":{name:"蓝色生命石", },
    "stone_speed_3":{name:"蓝色疾风石", },
    "stone_tenacity_3":{name:"蓝色恩惠石", },
    "stone_piece_atk_3":{name:"蓝色强攻石碎片", piece:5, },
    "stone_piece_crit_3":{name:"蓝色致命石碎片", piece:5, },
    "stone_piece_def_3":{name:"蓝色守护石碎片", piece:5, },
    "stone_piece_dodge_3":{name:"蓝色精巧石碎片", piece:5, },
    "stone_piece_hit_3":{name:"蓝色鹰眼石碎片", piece:5, },
    "stone_piece_hp_3":{name:"蓝色生命石碎片", piece:5, },
    "stone_piece_speed_3":{name:"蓝色疾风石碎片", piece:5, },
    "stone_piece_tenacity_3":{name:"蓝色恩惠石碎片", piece:5, },
    "stone_atk_4":{name:"紫色强攻石", },
    "stone_crit_4":{name:"紫色致命石", },
    "stone_def_4":{name:"紫色守护石", },
    "stone_dodge_4":{name:"紫色精巧石", },
    "stone_hit_4":{name:"紫色鹰眼石", },
    "stone_hp_4":{name:"紫色生命石", },
    "stone_speed_4":{name:"紫色疾风石", },
    "stone_tenacity_4":{name:"紫色恩惠石", },
    "stone_piece_atk_4":{name:"紫色强攻石碎片", piece:10, },
    "stone_piece_crit_4":{name:"紫色致命石碎片", piece:10, },
    "stone_piece_def_4":{name:"紫色守护石碎片", piece:10, },
    "stone_piece_dodge_4":{name:"紫色精巧石碎片", piece:10, },
    "stone_piece_hit_4":{name:"紫色鹰眼石碎片", piece:10, },
    "stone_piece_hp_4":{name:"紫色生命石碎片", piece:10, },
    "stone_piece_speed_4":{name:"紫色疾风石碎片", piece:10, },
    "stone_piece_tenacity_4":{name:"紫色恩惠石碎片", piece:10, },
    "stone_atk_5":{name:"橙色强攻石", },
    "stone_crit_5":{name:"橙色致命石", },
    "stone_def_5":{name:"橙色守护石", },
    "stone_dodge_5":{name:"橙色精巧石", },
    "stone_hit_5":{name:"橙色鹰眼石", },
    "stone_hp_5":{name:"橙色生命石", },
    "stone_speed_5":{name:"橙色疾风石", },
    "stone_tenacity_5":{name:"橙色恩惠石", },
    "stone_piece_atk_5":{name:"橙色强攻石碎片", piece:20, },
    "stone_piece_crit_5":{name:"橙色致命石碎片", piece:20, },
    "stone_piece_def_5":{name:"橙色守护石碎片", piece:20, },
    "stone_piece_dodge_5":{name:"橙色精巧石碎片", piece:20, },
    "stone_piece_hit_5":{name:"橙色鹰眼石碎片", piece:20, },
    "stone_piece_hp_5":{name:"橙色生命石碎片", piece:20, },
    "stone_piece_speed_5":{name:"橙色疾风石碎片", piece:20, },
    "stone_piece_tenacity_5":{name:"橙色恩惠石碎片", piece:20, },
    "stone_atk_6":{name:"红色强攻石", },
    "stone_crit_6":{name:"红色致命石", },
    "stone_def_6":{name:"红色守护石", },
    "stone_dodge_6":{name:"红色精巧石", },
    "stone_hit_6":{name:"红色鹰眼石", },
    "stone_hp_6":{name:"红色生命石", },
    "stone_speed_6":{name:"红色疾风石", },
    "stone_tenacity_6":{name:"红色恩惠石", },
    "stone_piece_atk_6":{name:"红色强攻石碎片", piece:30, },
    "stone_piece_crit_6":{name:"红色致命石碎片", piece:30, },
    "stone_piece_def_6":{name:"红色守护石碎片", piece:30, },
    "stone_piece_dodge_6":{name:"红色精巧石碎片", piece:30, },
    "stone_piece_hit_6":{name:"红色鹰眼石碎片", piece:30, },
    "stone_piece_hp_6":{name:"红色生命石碎片", piece:30, },
    "stone_piece_speed_6":{name:"红色疾风石碎片", piece:30, },
    "stone_piece_tenacity_6":{name:"红色恩惠石碎片", piece:30, },
    "stone_atk_7":{name:"金色强攻石", },
    "stone_crit_7":{name:"金色致命石", },
    "stone_def_7":{name:"金色守护石", },
    "stone_dodge_7":{name:"金色精巧石", },
    "stone_hit_7":{name:"金色鹰眼石", },
    "stone_hp_7":{name:"金色生命石", },
    "stone_speed_7":{name:"金色疾风石", },
    "stone_tenacity_7":{name:"金色恩惠石", },
    "stone_piece_atk_7":{name:"金色强攻石碎片", piece:30, },
    "stone_piece_crit_7":{name:"金色致命石碎片", piece:30, },
    "stone_piece_def_7":{name:"金色守护石碎片", piece:30, },
    "stone_piece_dodge_7":{name:"金色精巧石碎片", piece:30, },
    "stone_piece_hit_7":{name:"金色鹰眼石碎片", piece:30, },
    "stone_piece_hp_7":{name:"金色生命石碎片", piece:30, },
    "stone_piece_speed_7":{name:"金色疾风石碎片", piece:30, },
    "stone_piece_tenacity_7":{name:"金色恩惠石碎片", piece:30, },
    "stone_piece_random_2":{name:"绿色随机石碎片", use:true, },
    "stone_piece_random_3":{name:"蓝色随机石碎片", use:true, },
    "stone_piece_random_4":{name:"紫色随机石碎片", use:true, },
    "stone_piece_random_5":{name:"橙色随机石碎片", use:true, },
    "stone_piece_random_6":{name:"红色随机石碎片", use:true, },
    "stone_piece_random_7":{name:"金色随机石碎片", use:true, },
    "equip_compose_4_any":{name:"神金锭", },
    "equip_compose_4_a":{name:"4阶武具图纸", },
    "equip_compose_4_b":{name:"4阶防具图纸", },
    "equip_compose_4_c":{name:"4阶饰品图纸", },
    "equip_compose_4_extra":{name:"4阶龙石", },
};

Database.equips = {
    "amulet":{name:"护身符"},
    "armor":{name:"护肩"},
    "boots":{name:"靴子"},
    "certificate":{name:"证书"},
    "legs":{name:"护腿"},
    "mask":{name:"面罩"},
    "pet":{name:"宠物"},
    "ring":{name:"戒指"},
    "shield":{name:"盾牌"},
    "weapon":{name:"武器"},
};

Database.goblin_item = {
    "1":{item_id:"coin", count:1000, buy:2, },
    "2":{item_id:"coin", count:500, buy:2, },
    "3":{item_id:"summon_book", count:5, buy:1, },
    "4":{item_id:"summon_book", count:2, buy:1, },
    "5":{item_id:"stone_piece_random_3", count:100, buy:1, },
    "6":{item_id:"stone_piece_random_4", count:100, buy:1, },
    "7":{item_id:"stone_piece_random_5", count:100, buy:1, },
    "8":{item_id:"stone_piece_random_6", count:100, buy:1, },
    "9":{item_id:"stone_piece_random_7", count:100, buy:1, },
    "10":{item_id:"food_2", count:30, buy:1, },
    "11":{item_id:"food_3", count:30, buy:1, },
    "12":{item_id:"food_4", count:30, buy:1, },
    "13":{item_id:"food_5", count:30, buy:1, },
    "14":{item_id:"food_6", count:30, buy:1, },
    "15":{item_id:"dungeon_dice", count:5, buy:1, },
    "16":{item_id:"hero_upgrade_card_piece", count:3, buy:1, },
    "17":{item_id:"summon_book", count:5, buy:2, },
    "18":{item_id:"summon_book", count:2, buy:2, },
    "19":{item_id:"stone_piece_random_3", count:100, buy:2, },
    "20":{item_id:"stone_piece_random_4", count:100, buy:2, },
    "21":{item_id:"stone_piece_random_5", count:100, buy:2, },
    "22":{item_id:"stone_piece_random_6", count:100, buy:2, },
    "23":{item_id:"stone_piece_random_7", count:100, buy:2, },
    "24":{item_id:"food_2", count:30, buy:2, },
    "25":{item_id:"food_3", count:30, buy:2, },
    "26":{item_id:"food_4", count:30, buy:2, },
    "27":{item_id:"food_5", count:30, buy:2, },
    "28":{item_id:"food_6", count:30, buy:2, },
    "29":{item_id:"dungeon_dice", count:5, buy:2, },
    "30":{item_id:"hero_upgrade_card_piece", count:3, buy:2, },
};

Database.goblin_reduce = {
    "9": 8,
    "10": 5,
    "11": 5,
    "12": 3,
};

Database.heros = {
    "80005":{name:"潘多拉", cls:"X", },
    "80010":{name:"青鸾", cls:"X", },
    "80003":{name:"路西法", cls:"X", },
    "80001":{name:"妲己", cls:"X", },
    "80008":{name:"波塞冬", cls:"X", },
    "80006":{name:"美杜莎", cls:"X", },
    "80004":{name:"伏羲", cls:"X", },
    "80009":{name:"苍龙", cls:"X", },
    "80002":{name:"哈迪斯", cls:"X", },
    "70007":{name:"黑衣剑士", cls:"SSS+", },
    "70006":{name:"本子娜", cls:"SSS+", },
    "70003":{name:"枭之店长", cls:"SSS+", },
    "70012":{name:"吊车尾大王", cls:"SSS+", },
    "70014":{name:"真白骑士姬", cls:"SSS+", },
    "70008":{name:"雅典娜", cls:"SSS+", },
    "70015":{name:"红发之皇", cls:"SSS+", },
    "70009":{name:"小狮郎", cls:"SSS+", },
    "70010":{name:"静电萌宠", cls:"SSS+", },
    "70011":{name:"黄色闪光", cls:"SSS+", },
    "70018":{name:"鼬神", cls:"SSS+", },
    "70016":{name:"狗哥", cls:"SSS+", },
    "70017":{name:"泰坦神王", cls:"SSS+", },
    "70005":{name:"金木小天使", cls:"SSS+", },
    "70001":{name:"吾王", cls:"SSS+", },
    "70004":{name:"荣耀大剑", cls:"SSS+", },
    "70019":{name:"银酱", cls:"SSS+", },
    "70013":{name:"草帽小子", cls:"SSS+", },
    "70020":{name:"基神", cls:"SSS+", },
    "70002":{name:"黑焰射手", cls:"SSS+", },
    "70022":{name:"欠雷", cls:"SSS", },
    "70048":{name:"司令官大哥", cls:"SSS", },
    "70049":{name:"T800", cls:"SSS", },
    "70030":{name:"ZERO", cls:"SSS", },
    "70036":{name:"传说中的肥羊", cls:"SSS", },
    "70054":{name:"绿之勇者", cls:"SSS", },
    "70021":{name:"红之骑士", cls:"SSS", },
    "70023":{name:"吃撑", cls:"SSS", },
    "70043":{name:"霍比特小能手", cls:"SSS", },
    "70037":{name:"超级射击子", cls:"SSS", },
    "70046":{name:"崇明四郎", cls:"SSS", },
    "70053":{name:"第六天大魔王", cls:"SSS", },
    "70028":{name:"大蛇", cls:"SSS", },
    "70029":{name:"片翼天使", cls:"SSS", },
    "70040":{name:"拷贝忍者", cls:"SSS", },
    "70045":{name:"月下吸血鬼", cls:"SSS", },
    "70039":{name:"Lucy", cls:"SSS", },
    "70051":{name:"梦幻生物", cls:"SSS", },
    "70034":{name:"吕奉先", cls:"SSS", },
    "70031":{name:"SOS团长", cls:"SSS", },
    "70025":{name:"金色炮姐", cls:"SSS", },
    "70033":{name:"孔明", cls:"SSS", },
    "70035":{name:"小埋", cls:"SSS", },
    "70047":{name:"北斗霸主", cls:"SSS", },
    "70041":{name:"海贼猎人", cls:"SSS", },
    "70042":{name:"国王贡", cls:"SSS", },
    "70024":{name:"披萨魔女", cls:"SSS", },
    "70052":{name:"双子座", cls:"SSS", },
    "70027":{name:"最强佣兵", cls:"SSS", },
    "70050":{name:"第一歌姬", cls:"SSS", },
    "70038":{name:"甩葱女神", cls:"SSS", },
    "70032":{name:"妖精女王", cls:"SSS", },
    "70044":{name:"孙悟空", cls:"SSS", },
    "70026":{name:"三无少女", cls:"SSS", },
    "60016":{name:"艾雪", },
    "60040":{name:"恶魔猎手", },
    "80010":{name:"潘多拉", },
};
